# Generated by Django 4.2.20 on 2025-03-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_create_admin'),
        ('booking', '0003_room_is_available_alter_hotelinfo_email_and_more'),
    ]

    operations = [
    ]
